simple_mailchimp.settings:
  type: config_object
  label: 'Settings'
  mapping:
    apiKey:
      label: 'API Key'
      type: text
    listId:
      label: 'List ID'
      type: text
    status:
      label: 'Status'
      type: text
    text:
      label: 'Text'
      type: text
    formIds:
      label: 'Form IDs'
      type: sequence
    interestGroup:
      label: 'Interest Group'
      type: text
